version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            cat .cirlceci/config.yml
            echo '^^^That should look familiar^^^'
